config/routes.rb
Finance::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root :to => 'transactions#index'

  resources :accounts, except: [:show] 
  resources :transactions
  resources :analytics, only: [:index] do
    collection do
      get :month
      get :accounts
    end
  end

  resources :categories  do
    post :rebuild, :on => :collection
  end

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id        :integer          not null, primary key
#  name      :string(255)      not null
#  user_id   :integer          not null
#  parent_id :integer
#  lft       :integer
#  rgt       :integer
#  depth     :integer
#  type_id   :integer          not null
#

class Category < ActiveRecord::Base
  acts_as_nested_set
  include TheSortableTree::Scopes

  attr_accessible :name, :parent_id, :type_id, :user_id

  has_many :transactions, :dependent => :destroy

  belongs_to :user
  validates :user_id, :presence => true

  validates :type_id, :presence => true #, :inludes => { 0..[].length}

  Transaction::TYPES.each_with_index do |type, i|
    scope "#{type}".to_sym, where(type_id: i)
  end

  def type
    Transaction::TYPES[type_id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include TheSortableTreeController::Rebuild

  before_filter :authenticate_user!
  before_filter :get_category_by_id, only: [:edit, :show, :update, :destroy]

  respond_to :json, :html

  def index
    @categories_outlay = current_user.categories.where("type_id = ?",0).nested_set.all
    @categories_income = current_user.categories.where("type_id = ?",1).nested_set.all

    respond_with do |format|
      format.html { render :index }
    end
  end

  def new
    @category = Category.new :type_id => Transaction::TYPES.index(params[:type]) || Transaction::TYPES.index('outlay')

    respond_with(@category, :location => categories_path)
  end

  def edit
  end

  def create
    @category = current_user.categories.build(params[:category])

    flash[:notice] = 'Account was successfully created.' if @category.save

    respond_with(@category, :location => categories_path+"##{@category.type}")
  end

  def update
    flash[:notice] = 'Account was successfully updated.' if @category.update_attributes(params[:category])

    respond_with(@category, :location => categories_path+"##{@category.type}")
  end

  def destroy
    flash[:notice] = 'Account was successfully deleted.' if @category.destroy

    respond_with(@category, :location => categories_path+"##{@category.type}")
  end

  private

  def get_category_by_id
    @category = current_user.categories.find_by_id(params[:id])

    if @category.nil?
      redirect_to categories_path, alert: "Can't get such category."
    end
  end

end

app/views/categories/_form.html.erb
<%= simple_form_for category, :html => { :class => "form-horizontal"} do |f| %>
  <legend><%= controller.action_name.capitalize %> Category</legend>

  <!-- Display Errors -->
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
      <% category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.input :name %>
  <%= f.input :type_id, :as => :hidden %>

  <div class="form-actions">
    <%= f.submit :class => 'btn btn-primary' %>
    <%= link_to "Cancel", categories_path, :class=>"btn" %>
  </div>
<% end %>

<%= debug(params) if Rails.env.development? %>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h2>Categories list</h2>

<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#outlay" data-toggle="tab">Outlay</a></li>
  <li><a href="#income" data-toggle="tab">Income</a></li>

</ul>

<div class="tab-content">
  <div class="tab-pane active" id="outlay">
    <%= sortable_tree(@categories_outlay, :path => 'categories/sortable/base', :type => :sortable, :title => :name, :new_url => new_category_path(:type => 'outlay') ) %>
  </div>

  <div class="tab-pane" id="income">
    <%= sortable_tree(@categories_income, :path => 'categories/sortable/base', :type => :sortable, :title => :name, :new_url => new_category_path(:type => 'income') ) %>
  </div>
</div>

<%= javascript_tag do %>
  jQuery(function() {
    $("#myTab a[href='"+window.location.hash+"']").tab('show');
    window.location.hash = '#';
  });
<% end %>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>