config/routes.rb
Finance::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root :to => 'transactions#index'

  resources :accounts, except: [:show] 
  resources :transactions
  resources :analytics, only: [:index] do
    collection do
      get :month
      get :accounts
    end
  end

  resources :categories  do
    post :rebuild, :on => :collection
  end

end

app/models/transaction_type.rb
# == Schema Information
#
# Table name: transaction_types
#
#  id          :integer          not null, primary key
#  name        :string(255)      not null
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class TransactionType < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true

  has_many :transaction
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  include PeriodHelper
  before_filter :authenticate_user!

  before_filter :get_categories_all, only: [:index]
  before_filter :get_account_list, only: [:index, :new, :create, :edit, :update]
  before_filter :get_transaction_by_id, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @period = process_period(params[:period], 1.month.ago.to_date, Date.today)
    @transactions = current_user.transactions.with_type.with_account.with_category.period(@period[:start], @period[:finish])

    respond_with do |format|
      format.html { render partial: 'transaction_list', :locals => {accounts: @accounts, categories: @categories} } if params[:partial]
      format.json { render json: TransactionsDatatable.new(view_context, @transactions, @accounts, @categories) }
    end
  end

  def show
  end

  def new
    default = {account_id: @accounts.first.id, date: Date.current().to_s(:db)}
    default[:transaction_type_id] = TransactionType.find_by_name(params[:type]).id

    @transaction = Transaction.new(default)
    @categories = get_category_list(@transaction[:transaction_type_id] - 1)

    respond_with do |format|
      format.html { render partial: transaction_edit_form, locals: {categories: @categories, accounts: @accounts, transaction: @transaction} }
    end
  end

  def create
    @transaction = current_user.transactions.build(params[:transaction])
    @categories = {@transaction.transaction_type_name => get_category_list(@transaction.transaction_type_id - 1)}

    respond_to do |format|
      if @transaction.save
        format.json { render json: TransactionsDatatable.new(view_context, [@transaction], @accounts, @categories) }
      else
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @categories = get_category_list(@transaction.transaction_type_id - 1)

    respond_with do |format|
      format.html { render partial: transaction_edit_form, locals: {categories: @categories, accounts: @accounts, transaction: @transaction} }
    end
  end

  def update
    @categories = {@transaction.transaction_type_name => get_category_list(@transaction.transaction_type_id - 1)}

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.json { render json: TransactionsDatatable.new(view_context, [@transaction], @accounts, @categories), status: :ok }
      else
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    flash[:notice] = 'Transaction was successfully delete.' if @transaction.destroy

    respond_to do |format|
      format.json { render json: @transaction.id }
    end
  end

  private

  def get_categories_all
    @categories = {
        "outlay" => current_user.categories.outlay.nested_set,
        "income" => current_user.categories.income.nested_set
    }
    if @categories["outlay"].empty?
      redirect_to categories_path+'#outlay', alert: "Please, create at least one outlay categories."
    elsif @categories["income"].empty?
      redirect_to categories_path+'#income', alert: "Please, create at least one income categories."
    end
  end

  def get_category_list(type_id)
    @categories = current_user.categories.where("type_id = ?", type_id).nested_set
  end

  def get_account_list
    @accounts = current_user.accounts.all

    redirect_to accounts_path, alert: "Please, create at least one account." if @accounts.empty?
  end

  def get_transaction_by_id
    @transaction = current_user.transactions.find_by_id(params[:id])

    redirect_to transactions_path, alert: "Can't get such transaction." if @transaction.nil?
  end

  def transaction_edit_form
    case @transaction.transaction_type_name
      when 'outlay'
        return 'edit_outlay'
      when 'income'
        return 'edit_income'
      when 'transfer'
        return 'edit_transfer'
    end
  end

end

app/views/transactions/_edit_income.html.erb
<div class="modal hide fade" id="myModal">
<%= simple_form_for(transaction, remote: true, :format => :json, :html => { :class => "form-horizontal trans-edit"}) do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><%= controller.action_name.capitalize %> Income</h3>
  </div>
  <div class="modal-body">
    <div id="alert-area-modal"></div>
    
    <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
    <%= f.input :text, :label => 'Description' %>
    <%= f.input :amount %>
    
    <%= f.input :transaction_type_id, as: :hidden %>
    <%= f.association :account, collection: accounts.map{ |u| ["#{u.balance.currency.symbol} #{u.name}", u.id]} %>
    <%= f.association :category, collection: categories.map { |i| ["#{'-' * i.depth} #{i.name}", i.id] }  %>
  </div>
  <div class="modal-footer">
    <%= link_to "Cancel", '#', :class=>"btn", :"data-dismiss" => "modal" %>
    <%= f.submit :class=>"btn btn-primary" %>
  </div>

  <%= debug(transaction) if Rails.env.development? %>
<% end %>
</div>

app/views/transactions/_edit_outlay.html.erb
<div class="modal hide fade" id="myModal">
<%= simple_form_for(transaction, remote: true, :format => :json, :html => { :class => "form-horizontal trans-edit"}) do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><%= controller.action_name.capitalize %> Outlay</h3>
  </div>
  <div class="modal-body">
    <div id="alert-area-modal"></div>
    
    <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
    <%= f.input :text, :label => 'Description' %>
    <%= f.input :amount %>
    
    <%= f.input :transaction_type_id, as: :hidden %>
    <%= f.association :account, collection: accounts.map{ |u| ["#{u.balance.currency.symbol} #{u.name}", u.id]} %>
    <%= f.association :category, collection: categories.map { |i| ["#{'-' * i.depth} #{i.name}", i.id] }  %>

  </div>
  <div class="modal-footer">
    <%= link_to "Cancel", '#', :class=>"btn", :"data-dismiss" => "modal" %>
    <%= f.submit :class=>"btn btn-primary" %>
  </div>

<% end %>
</div>

app/views/transactions/_edit_transfer.html.erb
<div class="modal hide fade" id="myModal">
<%= simple_form_for(transaction, remote: true, :format => :json, :html => { :class => "form-horizontal trans-edit"}) do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><%= controller.action_name.capitalize %> Transfer</h3>
  </div>
  <div class="modal-body">
    <div id="alert-area-modal"></div>
    
    <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
    <%= f.input :text, :label => 'Description' %>

    <p>From</p>
    <%= f.input :amount %>
    <%= f.association :account, collection: accounts.map{ |u| ["#{u.balance.currency.symbol} #{u.name}", u.id]} %>

    <p>To</p>
    <%= f.input :trans_amount, label: "Amount"  %>
    <%= f.association :trans_account, collection: accounts.map{ |u| ["#{u.balance.currency.symbol} #{u.name}", u.id]}, label: "Account" %>

    <%= f.input :transaction_type_id, as: :hidden %>
  </div>
  <div class="modal-footer">
    <%= link_to "Cancel", '#', :class=>"btn", :"data-dismiss" => "modal" %>
    <%= f.submit :class=>"btn btn-primary" %>
  </div>

  <%= debug(transaction) if Rails.env.development? %>
<% end %>
</div>

app/views/transactions/_form.html.erb
<%= simple_form_for(transaction, :html => { :class => "form-horizontal"}) do |f| %>
    <legend><%= controller.action_name.capitalize %> Transaction</legend>

    <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
    <%= f.input :text, :label => 'Description' %>
    <%= f.input :amount, as: :float, :input_html => { value: transaction.cents_to_money } %>

    <%= f.association :transaction_type, collection: transaction_types %>
    <%= f.association :account, collection: accounts %>

  <div class="form-actions">
    <%= f.submit :class=>"btn btn-primary" %>
    <%= link_to "Cancel", root_path, :class=>"btn" %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<tr id="<%= dom_id(transaction) %>" class="<%= transaction.transaction_type_name %>" >
  <td><%= best_in_place transaction, :date, :type => :date %></td>
  <td><%= best_in_place transaction, :text, :type => :input %></td>

  <% if transaction.type_transfer? %>
    <td>
      <div>
        <div><%= transaction.transaction_type_name %></div>
        <div class="direction"> 
          from:
          <div class="divider"></div>
          to:
        </div>
      </div>
    </td>
    <td>
      <div><div>
        <%= best_in_place transaction, :amount, :type => :input %>
        <div class="divider"></div>
        <%= best_in_place transaction, :trans_amount, :type => :input %>
      </div></div>
    </td>
    <td>
      <div><div>
        <%= best_in_place transaction, :account_id, :type => :select, :collection => accounts_list %>
        <div class="divider"></div>
        <%= best_in_place transaction, :trans_account_id, :type => :select, :collection => accounts_list %>
      </div></div>
    </td>
    <td></td>
  <% else %>
    <td><%= transaction.transaction_type_name %></td>
    <td><%= best_in_place transaction, :amount, :type => :input %></td>
    <td><%= best_in_place transaction, :account_id, :type => :select, :collection => accounts_list %></td>
    <td><%= best_in_place transaction, :category_id, :type => :select, :collection => categories[transaction.transaction_type_name].map { |i| [i.id, "#{'-' * i.depth} #{i.name}"] }  %> </td>
  <% end %>
  

  <td>
    <ul class="nav nav-pills">
      <li><%= link_to [:edit, transaction], remote: true, class: "transaction-edit" do %><%= glyph(:pencil) %><% end %></li>
      <li><%= link_to transaction, confirm: 'Are you sure?', method: :delete, :remote => true, class: "transaction-delete", "data-type" => :json do %><i class="icon-trash"></i><% end %></li>
    </ul>
  </td>
</tr>

app/views/transactions/_transaction_list.html.erb
<table id="transactions-list" class="display table table-striped transactions-list">
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Type</th>
      <th>Amount</th>
      <th>Account</th>
      <th>Category</th>
      <th></th>
    </tr>
  </thead>
  <tbody>

  <%= render partial: 'transaction', :collection => @transactions, 
    :locals => { accounts_list: accounts.map{ |u| [u.id, "#{u.balance.currency.symbol} #{u.name}"]}, categories: categories } %>

  </tbody>
</table>

app/views/transactions/index.html.erb
<div id="transactions">

  <h2>Transactions list</h2>

  <div class="btn-group transaction-new btn-new">
    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
      <%= glyph(:plus, :white) %> New <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Outlay", new_transaction_path(:type => "outlay"), remote: true %></li>
      <li><%= link_to "Income", new_transaction_path(:type => "income"), remote: true %></li>
      <li><%= link_to "Transfer", new_transaction_path(:type => "transfer"), remote: true %></li>
    </ul>
  </div>

  <%=  form_tag(transactions_path, method: :get, :class => "form-inline select-period") do  %>
    <%= text_field_tag 'period[start]', @period[:start], class: "datepicker input-small" %>
    <%= text_field_tag 'period[finish]', @period[:finish], class: "datepicker input-small" %>

    <%= submit_tag "Go", :class=>"btn" %>
  <% end %>

	<%= render 'transaction_list', accounts: @accounts, categories: @categories %>
</div>