config/routes.rb
Finance::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root :to => 'transactions#index'

  resources :accounts, except: [:show] 
  resources :transactions
  resources :analytics, only: [:index] do
    collection do
      get :month
      get :accounts
    end
  end

  resources :categories  do
    post :rebuild, :on => :collection
  end

end

app/views/layouts/_func_menu.html.erb
<ul class="nav nav-list bs-docs-sidenav">
  <li class="<%= current_page?(transactions_path) ? "active" : "" %>" ><%= link_to "Transactions", transactions_path %></li>
  <li class="<%= current_page?(accounts_path) ? "active" : "" %>" ><%= link_to "Accounts", accounts_path %></li>
  <li class="<%= current_page?(categories_path) ? "active" : "" %>" ><%= link_to "Categories", categories_path %></li>
  <li class="nav-header">Analytics</li>
  <li class="<%= current_page?(analytics_path) ? "active" : "" %>" ><%= link_to "Outlay trend", analytics_path %></li>
  <li class="<%= current_page?(month_analytics_path) ? "active" : "" %>" ><%= link_to "Month report", month_analytics_path %></li>
  <li class="<%= current_page?(accounts_analytics_path) ? "active" : "" %>" ><%= link_to "Account's balance trend", accounts_analytics_path %></li>
</ul>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'Home Finance', root_path, :class => "brand" %>
      <div class="container nav-collapse">
        <ul class="nav pull-right">

          <% if user_signed_in? %>
            <li class="dropdown"> 
              <%= link_to '#', class: "dropdown-toggle", 'data-toggle' => "dropdown" do %>
                Logged in as <strong><%= current_user.email %></strong>
              <% end %>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
          
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finance</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body data-spy="scroll" data-target=".bs-docs-sidebar">
<%= render 'layouts/header', current_user: current_user %>
<div class="container-fluid">

  <div class="row-fluid">
    <div class="span2 bs-docs-sidebar" id="menu">
      <%= render 'layouts/func_menu' if signed_in? %>
    </div>
    <div class="span8" id="main">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
    <div class="span2" id="widgets">
      <%= render "accounts/balance_widget", accounts: @accounts if @accounts %>
    </div>
  </div>

</div>

<%= debug(params) if Rails.env.development? %>
<div class="row" id="modal"></div>
<div class="row" id="alert-area"></div>

</body>
</html>