config/routes.rb
Finance::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root :to => 'transactions#index'

  resources :accounts, except: [:show] 
  resources :transactions
  resources :analytics, only: [:index] do
    collection do
      get :month
      get :accounts
    end
  end

  resources :categories  do
    post :rebuild, :on => :collection
  end

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id            :integer          not null, primary key
#  name          :string(255)      not null
#  description   :string(255)
#  currency      :string(3)        not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  balance_cents :integer          default(0), not null
#  user_id       :integer          not null
#

class Account < ActiveRecord::Base
  attr_accessible :name, :description, :currency

  monetize :balance_cents
  validates :balance, :numericality => true
  validates :name, :presence => true, :length => {:maximum => 15},
            :uniqueness => {:scope => [:currency, :user_id], :message => "Account with such Name and Currency already exists"}
  validates :description, :length => {:maximum => 255}
  validates :currency, :presence => true, :length => {:is => 3}, :inclusion => {:in => Finance::Application.config.currency_list}

  has_many :transactions, :class_name => 'Transaction', :foreign_key => 'account_id'
  has_many :trans_transactions, :class_name => 'Transaction', :foreign_key => 'trans_account_id'

  belongs_to :user
  validates :user_id, :presence => true

  default_scope order(:id)

  before_create :set_balance

  def as_json (options = nil)
    options ||= {}
    options[:methods] = ((options[:methods] || []) + [:balance])
    super options
  end

  private
  def set_balance
    self.balance = 0
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_account_by_id, only: [:edit, :show, :update, :destroy]

  respond_to :html, :json

  def index
    @accounts = current_user.accounts.all

    respond_with do |format|
      format.json { render json: @accounts.to_json(:methods => [:balance]) }
    end
  end

  def new
    @account = Account.new
    respond_with(@account)
  end

  def edit
  end

  def create
    @account = current_user.accounts.build(params[:account])

    flash[:notice] = 'Account was successfully created.' if @account.save

    respond_with(@account, :location => accounts_path)
  end

  def update
    flash[:notice] = 'Account was successfully updated.' if @account.update_attributes(params[:account])

    respond_with(@account, :location => accounts_path)
  end

  def destroy
    flash[:notice] = 'Account was successfully deleted.' if @account.destroy

    respond_with(@account)
  end

  private

  def get_account_by_id
    @account = current_user.accounts.find_by_id(params[:id])

    if @account.nil?
      redirect_to accounts_path, alert: "Can't get such account."
    end
  end
end

app/views/accounts/_balance_widget.html.erb
<div id="balance_widget">
  <h3>Balance:</h3>
  <table>
  	<% accounts.each do |account| %>
  		<tr>
  		  <td class="key"><%= account.name %> <%= account.balance.currency.symbol %>:</td>
  		  <td class="value"><%= account.balance %></td>
  		</tr>
  	<% end %>
  </table>
</div>

app/views/accounts/_form.html.erb
<%= simple_form_for account, :html => { :class => "form-horizontal"} do |f| %>
  <legend><%= controller.action_name.capitalize %> Account</legend>

  <!-- Display Errors -->
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.input :currency, :collection => Finance::Application.config.currency_list, :selected => 'UAH'%>

  <div class="form-actions">
    <%= f.submit :class => 'btn btn-primary' %>
    <%= link_to "Cancel", accounts_path, :class=>"btn" %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<%= render 'form', account: @account %>

app/views/accounts/index.html.erb
<h2>Accounts list</h2>

<%= link_to glyph(:plus, :white)+' New', new_account_path, :class => 'btn btn-primary btn-new' %>

<table class="accounts-list table table-striped table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Currency</th>
      <th></th>
    </tr>
    </thead>
  <tbody>
  <% if @accounts.empty? %>
    <tr><td colspan="4">
      <i>There is no accounts, please create ...</i>
    </td></tr>
  <% end %>
  <% @accounts.each do |account| %>
    <tr>
      <td class="name"><%= account.name %></td>
      <td class="desc"><%= account.description %></td>
      <td class="currency"><%= account.currency %></td>
      <td class="control">
        <ul class="nav nav-pills">
          <li><%= link_to [:edit, account] do %><i class="icon-pencil"></i><% end %></li>
          <li><%= link_to account, confirm: 'Are you sure?', method: :delete do %><i class="icon-trash"></i><% end %></li>
        </ul>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/accounts/new.html.erb
<%= render 'form', account: @account %>